FROM eeacms/kgs:20.3.11
MAINTAINER "EEA: IDM2 B-Team"

ENV GRAYLOG_FACILITY=eni-plone
ENV SENTRY_DSN=

ENV SENTRY_SITE=
ENV SENTRY_RELEASE=20.3.11-9.3

COPY buildout.cfg /plone/instance/
RUN buildout
